### ISSUE TITLE
Add test infrastructure

### ISSUE THREAD

**Issue by MariusDieckmann** [ArunaStorage/proxy#7]
### Overview

Add tests to automatically test the full dataproxy. This includes, unit, integreation and e2e tests.

### Tasks
- [ ] Add unit tests for functions
- [ ] Add integration tests for high level features
- [ ] Add e2e tests with S3
- [ ] Automate tests via github actions
